import{i as a,S as m}from"./assets/vendor-BrddEoy-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const d="46051514-586eb2ff38120a16ff3b43d50",p="https://pixabay.com/api/";function g(o){const t=new URLSearchParams({key:d,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${p}?${t}`).then(s=>{if(!s.ok)throw new Error("Sorry, there are no images matching your search query. Please try again!");return s.json()})}function y(o){const t=document.querySelector(".gallery"),s=o.map(({webformatURL:i,largeImageURL:e,tags:r,likes:n,views:l,comments:u,downloads:f})=>`
    <a class="gallery-item" href="${e}">
      <div class="photo-card">
        <img src="${i}" alt="${r}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${n}</p>
          <p class="info-item"><b>Views:</b> ${l}</p>
          <p class="info-item"><b>Comments:</b> ${u}</p>
          <p class="info-item"><b>Downloads:</b> ${f}</p>
        </div>
      </div>
    </a>`).join("");t.innerHTML=s}const h=document.querySelector("#search-form"),b=document.querySelector("#gallery"),c=document.querySelector(".loader");h.addEventListener("submit",S);function S(o){o.preventDefault(),b.innerHTML="";const t=o.target.elements["search-query"].value.trim();if(t===""){a.error({title:"Error",message:"Please enter a search query!"});return}L(t)}function L(o){c.style.display="block",g(o).then(({hits:t,totalHits:s})=>{if(c.style.display="none",t.length===0){a.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t),new m(".gallery a").refresh(),s===0?a.info({title:"No Results",message:"No results found!",position:"topRight"}):a.success({title:"Success",message:`Found ${s} images!`,position:"topRight"})}).catch(t=>{c.style.display="none",a.error({title:"Error",message:t.message,position:"topRight"})})}
//# sourceMappingURL=index.js.map
